# Generated by Django 4.2.7 on 2023-11-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_artifact_id_alter_character_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Substat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("FIGHT_PROP_BASE_ATTACK", "Base ATK"),
                            ("FIGHT_PROP_HP", "Flat HP"),
                            ("FIGHT_PROP_ATTACK", "Flat ATK"),
                            ("FIGHT_PROP_DEFENSE", "Flat DEF"),
                            ("FIGHT_PROP_HP_PERCENT", "HP%"),
                            ("FIGHT_PROP_ATTACK_PERCENT", "ATK%"),
                            ("FIGHT_PROP_DEFENSE_PERCENT", "DEF%"),
                            ("FIGHT_PROP_CRITICAL", "Crit RATE"),
                            ("FIGHT_PROP_CRITICAL_HURT", "Crit DMG"),
                            ("FIGHT_PROP_CHARGE_EFFICIENCY", "Energy Recharge"),
                            ("FIGHT_PROP_HEAL_ADD", "Healing Bonus"),
                            ("FIGHT_PROP_ELEMENT_MASTERY", "Elemental Mastery"),
                            ("FIGHT_PROP_PHYSICAL_ADD_HURT", "Physical DMG Bonus"),
                            ("FIGHT_PROP_FIRE_ADD_HURT", "Pyro DMG Bonus"),
                            ("FIGHT_PROP_ELEC_ADD_HURT", "Electro DMG Bonus"),
                            ("FIGHT_PROP_WATER_ADD_HURT", "Hydro DMG Bonus"),
                            ("FIGHT_PROP_WIND_ADD_HURT", "Anemo DMG Bonus"),
                            ("FIGHT_PROP_ICE_ADD_HURT", "Cryo DMG Bonus"),
                            ("FIGHT_PROP_ROCK_ADD_HURT", "Geo DMG Bonus"),
                            ("FIGHT_PROP_GRASS_ADD_HURT", "Dendro DMG Bonus"),
                        ],
                        max_length=100,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=1, max_digits=5)),
                ("rolls", models.IntegerField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="FIGHT_PROP_ATTACK",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="FIGHT_PROP_ATTACK_PERCENT",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="FIGHT_PROP_BASE_ATTACK",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="FIGHT_PROP_CHARGE_EFFICIENCY",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="FIGHT_PROP_CRITICAL",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="FIGHT_PROP_CRITICAL_HURT",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="FIGHT_PROP_DEFENSE",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="FIGHT_PROP_DEFENSE_PERCENT",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="FIGHT_PROP_ELEC_ADD_HURT",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="FIGHT_PROP_ELEMENT_MASTERY",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="FIGHT_PROP_FIRE_ADD_HURT",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="FIGHT_PROP_GRASS_ADD_HURT",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="FIGHT_PROP_HEAL_ADD",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="FIGHT_PROP_HP",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="FIGHT_PROP_HP_PERCENT",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="FIGHT_PROP_ICE_ADD_HURT",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="FIGHT_PROP_PHYSICAL_ADD_HURT",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="FIGHT_PROP_ROCK_ADD_HURT",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="FIGHT_PROP_WATER_ADD_HURT",
        ),
        migrations.RemoveField(
            model_name="artifact",
            name="FIGHT_PROP_WIND_ADD_HURT",
        ),
        migrations.AlterField(
            model_name="player",
            name="uid",
            field=models.CharField(
                max_length=9,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="UID",
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="substats",
            field=models.ManyToManyField(to="app.substat"),
        ),
    ]
