# Generated by Django 4.2.7 on 2023-11-30 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_remove_artifact_substat_substat_artifact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SubstatField",
        ),
    ]
