# Generated by Django 4.2.7 on 2023-12-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_delete_substatfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="equiptype",
            field=models.CharField(
                choices=[
                    ("Flower", "Flower"),
                    ("Feather", "Feather"),
                    ("Sands", "Sands"),
                    ("Goblet", "Goblet"),
                    ("Circlet", "Circlet"),
                ],
                max_length=20,
            ),
        ),
    ]
