# Generated by Django 4.2.7 on 2024-01-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_artifact_level_alter_artifact_equiptype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="avatar",
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
