# Generated by Django 4.2.7 on 2024-01-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_alter_player_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="uid",
            field=models.CharField(
                db_index=True,
                max_length=9,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="UID",
            ),
        ),
    ]
