# Generated by Django 4.2.7 on 2024-01-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_alter_player_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="updated",
            field=models.DateTimeField(),
        ),
    ]
