# Generated by Django 4.2.7 on 2024-01-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_alter_player_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="level",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="substat",
            name="rolls",
            field=models.IntegerField(default=0),
        ),
    ]
