# Generated by Django 4.2.7 on 2024-01-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0018_alter_artifact_level_alter_substat_rolls"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="icon",
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
