# Generated by Django 4.2.7 on 2024-01-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0019_character_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="stat_atk",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="stat_cd",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="stat_cr",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="stat_def",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="stat_em",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="stat_er",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="stat_hp",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
