# Generated by Django 4.2.7 on 2024-01-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_alter_character_stat_cd_alter_character_stat_cr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="weapon_atk",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="character",
            name="weapon_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="weapon_substat_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FIGHT_PROP_HP_PERCENT", "HP%"),
                    ("FIGHT_PROP_ATTACK_PERCENT", "ATK%"),
                    ("FIGHT_PROP_DEFENSE_PERCENT", "DEF%"),
                    ("FIGHT_PROP_CRITICAL", "Crit RATE"),
                    ("FIGHT_PROP_CRITICAL_HURT", "Crit DMG"),
                    ("FIGHT_PROP_CHARGE_EFFICIENCY", "Energy Recharge"),
                    ("FIGHT_PROP_ELEMENT_MASTERY", "Elemental Mastery"),
                    ("FIGHT_PROP_PHYSICAL_ADD_HURT", "Physical DMG Bonus"),
                ],
                default=None,
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="weapon_substat_value",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="character",
            name="stat_cd",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="character",
            name="stat_cr",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="character",
            name="stat_er",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
