# Generated by Django 4.2.7 on 2023-11-30 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_artifact_substat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artifact",
            name="substat",
        ),
        migrations.AddField(
            model_name="substat",
            name="artifact",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="substats",
                to="app.artifact",
            ),
            preserve_default=False,
        ),
    ]
