# Generated by Django 4.2.7 on 2023-12-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_rename_artifact_substat_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="substat",
            name="ismainstat",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="substat",
            name="rolls",
            field=models.IntegerField(blank=True, max_length=1, null=True),
        ),
    ]
