name: Docker app test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app/

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t court-of-fontaine .
          docker save -o court-of-fontaine.tar court-of-fontaine

      - name: Set up Docker
        uses: actions/setup-docker@v2

      - name: Create db folder
        run: mkdir -p ${{ github.workspace }}/db


      - name: Run Docker container
        run: |
          docker load -i court-of-fontaine.tar
          docker run -v ${{ github.workspace }}/db -p 8000:8000 court-of-fontaine
